// 알림창 출력 요청
export const LOCAL_RQEUEST_ALERT = "LOCAL_RQEUEST_ALERT";

// 알림창 출력 clear
export const LOCAL_REQUEST_CLEAR_ALERT = "LOCAL_REQUEST_CLEAR_ALERT";
export const LOCAL_CLEAR_ALERT = "LOCAL_CLEAR_ALERT";

// 알림창 닫기 버튼 클릭
export const LOCAL_CLICK_ALERT_CLOSE = "LOCAL_CLICK_ALERT_CLOSE";
