export const LOAD_POST_DETAIL_REQUEST = "LOAD_POST_DETAIL_REQUEST";
export const LOAD_POST_DETAIL_SUCCESS = "LOAD_POST_DETAIL_SUCCESS";
export const LOAD_POST_DETAIL_FAILURE = "LOAD_POST_DETAIL_FAILURE";

// 좋아요 추가
export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

// 좋아요 취소
export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE";

// 댓글 입력
export const SUBMIT_COMMENT_REQUEST = "SUBMIT_COMMENT_REQUEST";
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS";
export const SUBMIT_COMMENT_FAILURE = "SUBMIT_COMMENT_FAILURE";

// TOC 설정
export const SET_TOC_REQUEST = "SET_TOC_REQUEST";
export const SET_TOC_SUCCESS = "SET_TOC_SUCCESS";
export const SET_TOC_FAILURE = "SET_TOC_FAILURE";