// 좋아한 포스트 불러오기
export const LOAD_LIKED_POSTS_REQUEST = "LOAD_LIKED_POSTS_REQUEST";
export const LOAD_LIKED_POSTS_SUCCESS = "LOAD_LIKED_POSTS_SUCCESS";
export const LOAD_LIKED_POSTS_FAILURE = "LOAD_LIKED_POSTS_FAILURE";

// 최근 읽은 포스트 불러오기
export const LOAD_READ_POSTS_REQUEST = "LOAD_READ_POSTS_REQUEST";
export const LOAD_READ_POSTS_SUCCESS = "LOAD_READ_POSTS_SUCCESS";
export const LOAD_READ_POSTS_FAILURE = "LOAD_READ_POSTS_FAILURE";
