// 검색한 정보 불러오기
export const LOAD_SEARCH_RESULT_REQUEST = "LOAD_SEARCH_RESULT_REQUEST";
export const LOAD_SEARCH_RESULT_SUCCESS = "LOAD_SEARCH_RESULT_SUCCESS";
export const LOAD_SEARCH_RESULT_FAILURE = "LOAD_SEARCH_RESULT_FAILURE";
