// 시리즈의 글 목록 불러오기
export const LOAD_SERIES_POSTS_REQUEST = 'LOAD_SERIES_POSTS_REQUEST';
export const LOAD_SERIES_POSTS_SUCCESS = 'LOAD_SERIES_POSTS_SUCCESS';
export const LOAD_SERIES_POSTS_FAILURE = 'LOAD_SERIES_POSTS_FAILURE';
