export const LOAD_USER_SETTING_REQUEST = "LOAD_USER_SETTING_REQUEST";
export const LOAD_USER_SETTING_SUCCESS = "LOAD_USER_SETTING_SUCCESS";
export const LOAD_USER_SETTING_FAILURE = "LOAD_USER_SETTING_FAILURE";
export const loadUserSettingRequest = (data) => ({
  type: LOAD_USER_SETTING_REQUEST,
  data,
});

export const SUBMIT_USER_SETTING_REQUEST = "SUBMIT_USER_SETTING_REQUEST";
export const SUBMIT_USER_SETTING_SUCCESS = "SUBMIT_USER_SETTING_SUCCESS";
export const SUBMIT_USER_SETTING_FAILURE = "SUBMIT_USER_SETTING_FAILURE";
export const submitUserSettingRequest = (data) => ({
  type: SUBMIT_USER_SETTING_REQUEST,
  data,
});

export const SUBMIT_MAIN_SETTING_REQUEST = "SUBMIT_MAIN_SETTING_REQUEST";
export const SUBMIT_MAIN_SETTING_SUCCESS = "SUBMIT_MAIN_SETTING_SUCCESS";
export const SUBMIT_MAIN_SETTING_FAILURE = "SUBMIT_MAIN_SETTING_FAILURE";
export const submitMainSettingRequest = (data) => ({
  type: SUBMIT_MAIN_SETTING_REQUEST,
  data,
});

export const SUBMIT_TITLE_SETTING_REQUEST = "SUBMIT_TITLE_SETTING_REQUEST";
export const SUBMIT_TITLE_SETTING_SUCCESS = "SUBMIT_TITLE_SETTING_SUCCESS";
export const SUBMIT_TITLE_SETTING_FAILURE = "SUBMIT_TITLE_SETTING_FAILURE";
export const submitTitleSettingRequest = (data) => ({
  type: SUBMIT_TITLE_SETTING_REQUEST,
  data,
});

export const SUBMIT_SOCIAL_SETTING_REQUEST = "SUBMIT_SOCIAL_SETTING_REQUEST";
export const SUBMIT_SOCIAL_SETTING_SUCCESS = "SUBMIT_SOCIAL_SETTING_SUCCESS";
export const SUBMIT_SOCIAL_SETTING_FAILURE = "SUBMIT_SOCIAL_SETTING_FAILURE";
export const submitSocialSettingRequest = (data) => ({
  type: SUBMIT_SOCIAL_SETTING_REQUEST,
  data,
});

export const SUBMIT_NOTIFY_SETTING_REQUEST = "SUBMIT_NOTIFY_SETTING_REQUEST";
export const SUBMIT_NOTIFY_SETTING_SUCCESS = "SUBMIT_NOTIFY_SETTING_SUCCESS";
export const SUBMIT_NOTIFY_SETTING_FAILURE = "SUBMIT_NOTIFY_SETTING_FAILURE";
export const submitNotifySettingRequest = (data) => ({
  type: SUBMIT_NOTIFY_SETTING_REQUEST,
  data,
});
