// 유저의 프로필 정보 불러오기
export const LOAD_USER_PROFILE_REQUEST = "LOAD_USER_PROFILE_REQUEST";
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_FAILURE = "LOAD_USER_PROFILE_FAILURE";
