// 유저의 프로필 정보 불러오기
export const LOAD_USER_PROFILE_REQUEST = "LOAD_USER_PROFILE_REQUEST";
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_FAILURE = "LOAD_USER_PROFILE_FAILURE";

// 유저가 작성한 글 목록 불러오기
export const LOAD_USER_POSTS_REQUEST = "LOAD_USER_POSTS_REQUEST";
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS";
export const LOAD_USER_POSTS_FAILURE = "LOAD_USER_POSTS_FAILURE";

//유저가 만든 시리즈 목록 불러오기
export const LOAD_USER_SERIES_LIST_REQUEST = "LOAD_USER_SERIES_LIST_REQUEST";
export const LOAD_USER_SERIES_LIST_SUCCESS = "LOAD_USER_SERIES_LIST_SUCCESS";
export const LOAD_USER_SERIES_LIST_FAILURE = "LOAD_USER_SERIES_LIST_FAILURE";

//유저 소개 불러오기
export const LOAD_USER_INTRODUCTION_REQUEST = "LOAD_USER_INTRODUCTION_REQUEST";
export const LOAD_USER_INTRODUCTION_SUCCESS = "LOAD_USER_INTRODUCTION_SUCCESS";
export const LOAD_USER_INTRODUCTION_FAILURE = "LOAD_USER_INTRODUCTION_FAILURE";

//유저가 작성한 글 목록에 포함된 태그들 불러오기
export const LOAD_USER_TAGS_REQUEST = "LOAD_USER_TAGS_REQUEST";
export const LOAD_USER_TAGS_SUCCESS = "LOAD_USER_TAGS_SUCCESS";
export const LOAD_USER_TAGS_FAILURE = "LOAD_USER_TAGS_FAILURE";