// 유저의 프로필 정보 불러오기
export const LOAD_USER_PROFILE_REQUEST = "NOTICE_LOAD_REQUEST";
export const LOAD_USER_PROFILE_SUCCESS = "NOTICE_LOAD_SUCCESS";
export const LOAD_USER_PROFILE_FAILURE = "NOTICE_LOAD_REQUEST";
